### ISSUE TITLE
GitHub to AMO

### ISSUE THREAD

**Issue by davidhedlund** [wagnerand/open-multiple-addresses#1]
Can you please add "Support site https://github.com/wagnerand/open-multiple-addresses" to https://addons.mozilla.org/en-US/firefox/addon/open-multiple-addresses/ ?

**Comment by wagnerand** [comment]
Can you elaborate on the reason for that?

**Comment by davidhedlund** [comment]
@wagnerand So people know where to submit bugs.

**Comment by wagnerand** [comment]
Do you experience an issue with the add-on?

**Comment by davidhedlund** [comment]
@wagnerand No, but I'm a GNU IceCat add-on maintainer. So I'm trying to put things together.

**Comment by wagnerand** [comment]
I added it as _Homepage_.

**Comment by davidhedlund** [comment]
@wagnerand Thank you.
